# Generated by Django 4.1.7 on 2023-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('Seat_Number', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
