# Generated by Django 4.1.7 on 2023-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course1', models.CharField(max_length=100)),
                ('course2', models.CharField(max_length=100)),
                ('course3', models.CharField(max_length=100)),
                ('course4', models.CharField(max_length=100)),
                ('course5', models.CharField(max_length=100)),
                ('course6', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=15),
        ),
    ]
