# Generated by Django 4.1.7 on 2023-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_courses_studentdetails_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=15),
        ),
    ]
