# Generated by Django 4.2 on 2023-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='Assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.CharField(default='Course 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=15),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.CharField(default='Assignment 1', max_length=600),
        ),
    ]
